global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'roman-converter'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: roman-converter
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: 8080
